version: "3.8"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - TZ=Asia/Hong_Kong
    volumes:
      - mosquitto-vol:/mosquitto

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on:
      - mosquitto
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Hong_Kong
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - zigbee2mqtt-vol:/app/data
      - /run/udev:/run/udev:ro

  homebridge:
    container_name: homebridge
    image: oznu/homebridge
    depends_on:
      - mosquitto
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Hong_Kong
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    volumes:
      - homebridge-vol:/homebridge

  nodered:
    container_name: nodered
    image: nodered/node-red
    depends_on:
      - mosquitto
      - homebridge
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - nodered-vol:/data
    environment:
      - TZ=Asia/Hong_Kong

  telegraf:
    container_name: telegraf
    image: telegraf
    depends_on:
      - mosquitto
    restart: unless-stopped
    hostname: coziee.local
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
      - TZ=Asia/Hong_Kong
    volumes:
      - telegraf-vol:/etc/telegraf
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  mosquitto-vol:
    name: mosquitto-vol
  zigbee2mqtt-vol:
    name: zigbee2mqtt-vol
  homebridge-vol:
    name: homebridge-vol
  nodered-vol:
    name: nodered-vol
  telegraf-vol:
    name: telegraf-vol
