version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-config-vol:/mosquitto/config
      - mosquitto-data-vol:/mosquitto/data
      - mosquitto-log-vol:/mosquitto/log
    environment:
      - TZ=Asia/Hong_Kong

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on:
      - mosquitto
    restart: unless-stopped
    volumes:
      - zigbee2mqtt-vol:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    privileged: true
    environment:
      - TZ=Asia/Hong_Kong

  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    depends_on:
      - mosquitto
    restart: unless-stopped
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Asia/Hong_Kong
    volumes:
      - homebridge-vol:/homebridge

  influxdb:
    container_name: influxdb
    image: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data-vol:/var/lib/influxdb2
      - influxdb-config-vol:/etc/influxdb2
    environment:
      - TZ=Asia/Hong_Kong

  telegraf:
    container_name: telegraf
    image: telegraf
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped
    volumes:
      - telegraf-vol:/etc/telegraf
    environment:
      - TZ=Asia/Hong_Kong

  nodered:
    container_name: nodered
    image: nodered/node-red
    depends_on:
      - mosquitto
      - homebridge
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - nodered-vol:/data
    environment:
      - TZ=Asia/Hong_Kong

volumes:
  mosquitto-config-vol:
    name: mosquitto-config-vol
  mosquitto-data-vol:
    name: mosquitto-data-vol
  mosquitto-log-vol:
    name: mosquitto-log-vol
  influxdb-data-vol:
    name: influxdb-data-vol
  influxdb-config-vol:
    name: influxdb-config-vol
  telegraf-vol:
    name: telegraf-vol
  zigbee2mqtt-vol:
    name: zigbee2mqtt-vol
  homebridge-vol:
    name: homebridge-vol
  nodered-vol:
    name: nodered-vol
